plant_dict = {
    'Daylilies': 'https://garden.org/plants/view/181473/Daylilies-Hemerocallis/',
    'Irises': 'https://garden.org/plants/view/181474/Irises-Iris/',
    'Roses': 'https://garden.org/plants/view/181506/Roses-Rosa/',
    'Sempervivum': 'https://garden.org/plants/view/186377/Sempervivum/',
    'Hostas': 'https://garden.org/plants/view/181510/Hostas-Hosta/',
    'Lilies': 'https://garden.org/plants/view/77555/Lilies-Lilium/',
    'Dahlias': 'https://garden.org/plants/view/76165/Dahlias-Dahlia/',
    'Peonies': 'https://garden.org/plants/view/530825/Peonies-Paeonia/',
    'Salvias': 'https://garden.org/plants/view/228296/Salvias-Salvia/',
    'Abelias': 'https://garden.org/plants/view/242735/Abelias-Vesalea/',
    'Abutilons': 'https://garden.org/plants/view/242733/Abutilons-Callianthe/',
    'Adeniums': 'https://garden.org/plants/view/242253/Adeniums-Adenium/',
    'Aeoniums': 'https://garden.org/plants/view/649201/Aeoniums-Aeonium/',
    'Agapanthus': 'https://garden.org/plants/view/75143/Lily-of-the-Nile-Agapanthus/',
    'Agaves': 'https://garden.org/plants/view/242254/Agaves-Agave/',
    'Aglaonemas': 'https://garden.org/plants/view/71544/Aglaonemas-Aglaonema/',
    'Air Plants': 'https://garden.org/plants/view/232959/Air-Plants-Tillandsia/',
    'Aloes': 'https://garden.org/plants/view/242252/Aloes-Aloe/',
    'Amaryllis': 'https://garden.org/plants/view/76980/Amaryllis/',
    'Amorphophallus': 'https://garden.org/plants/view/243338/Voodoo-Plant-Amorphophallus/',
    "Angel's Trumpets": 'https://garden.org/plants/view/236057/Angels-Trumpets-Brugmansia/',
    'Anise Hyssops': 'https://garden.org/plants/view/242700/Anise-Hyssops-Agastache/',
    'Anthuriums': 'https://garden.org/plants/view/538637/Anthuriums-Anthurium/',
    'Apples': 'https://garden.org/plants/view/86564/Apples-Malus/',
    'Apricots': 'https://garden.org/plants/view/114689/Apricots-Prunus-armeniaca/',
    'Arborvitaes': 'https://garden.org/plants/view/710373/Arborvitaes-Thuja/',
    'Arisaemas': 'https://garden.org/plants/view/528695/Arisaemas-Arisaema/',
    'Artichokes': 'https://garden.org/plants/view/87062/Artichokes-Cynara-scolymus/',
    'Arums': 'https://garden.org/plants/view/641388/Arums-Arum/',
    'Asparagus': 'https://garden.org/plants/view/86226/Asparagus-Asparagus-officinalis/',
    'Asters': 'https://garden.org/plants/view/232412/Asters-Aster/',
    'Astilbes': 'https://garden.org/plants/view/242590/Astilbes-Astilbe/',
    'Astragaluses': 'https://garden.org/plants/view/536504/Astragaluses-Astragalus/',
}